

import javax.swing.*;
import IngeSoft.PI2.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class VisitatoreForm extends javax.swing.JDialog {

    private MainPI2Form mainForm;
    private IngeSoft.PI2.Visitatore visitatore;
    private SimpleDateFormat formatDate;
    
    /**
     * Creates new form VisitatoreForm
     */
    public VisitatoreForm( java.awt.Frame parent, boolean modal, MainPI2Form _mainForm ) {                
        this( parent, modal, _mainForm, null );
    }
    
    public VisitatoreForm(java.awt.Frame parent, boolean modal, MainPI2Form _mainForm, IngeSoft.PI2.Visitatore _visitatore ) {
        super(parent, modal);
        initComponents();
        
        mainForm = _mainForm;
        visitatore = _visitatore;
        
        formatDate = new SimpleDateFormat("dd/MM/yyyy");
        
        // codice fiscale non modificabile
        if (visitatore != null)
        {
            txtNome.setText(visitatore.getNome());
            txtCognome.setText(visitatore.getCognome());
            txtCodiceFiscale.setText(visitatore.getCodiceFiscale());
            
            txtCodiceFiscale.setEditable(false);
            
            // lista visite
            AggiornaListaVisite();
        }
        else
        {
            visitatore = new IngeSoft.PI2.Visitatore();
        }
        
        // evento selezione liste
        tblEspositori.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
                    public void valueChanged(ListSelectionEvent event) {
                        btnDelValutazione.setEnabled( tblEspositori.getSelectedRow() >= 0);
                    }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodiceFiscale = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCognome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstVisite = new javax.swing.JList();
        lblValutazioni = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEspositori = new javax.swing.JTable();
        btnAddVisita = new javax.swing.JButton();
        btnDelVisita = new javax.swing.JButton();
        btnAddValutazione = new javax.swing.JButton();
        btnDelValutazione = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visitatore");

        jLabel1.setText("Nome");

        jLabel2.setText("Cognome");

        jLabel3.setText("Codice Fiscale");

        jLabel4.setText("Giorni di visita effettuati");

        lstVisite.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstVisite.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstVisiteValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstVisite);

        lblValutazioni.setText("Espositori visitati il giorno:");
        lblValutazioni.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tblEspositori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Paese", "Area", "IVA", "Valutazione"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEspositori.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tblEspositori);

        btnAddVisita.setText("Aggiungi");
        btnAddVisita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddVisitaMouseClicked(evt);
            }
        });

        btnDelVisita.setText("Rimuovi");
        btnDelVisita.setEnabled(false);
        btnDelVisita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelVisitaMouseClicked(evt);
            }
        });

        btnAddValutazione.setText("Aggiungi");
        btnAddValutazione.setEnabled(false);
        btnAddValutazione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddValutazioneMouseClicked(evt);
            }
        });

        btnDelValutazione.setText("Rimuovi");
        btnDelValutazione.setEnabled(false);
        btnDelValutazione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDelValutazioneMouseClicked(evt);
            }
        });

        btnCancel.setText("Annulla");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                    .addComponent(txtCognome)
                                    .addComponent(txtCodiceFiscale)))
                            .addComponent(lblValutazioni, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddVisita, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(btnDelVisita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(2, 2, 2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDelValutazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddValutazione, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodiceFiscale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelVisita)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblValutazioni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnAddValutazione)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelValutazione))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOK)
                            .addComponent(btnCancel))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        dispose();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void lstVisiteValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstVisiteValueChanged
        btnDelVisita.setEnabled( lstVisite.getSelectedIndex() >= 0);
        
        AggiornaListaValutazioni();
    }//GEN-LAST:event_lstVisiteValueChanged

    private void btnAddVisitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddVisitaMouseClicked
        String data = JOptionPane.showInputDialog("Inserisci giorno (DD/MM/YYYY)");

        if (data != null)
        {
            GregorianCalendar date = new GregorianCalendar();

            try {
                date.setTime( formatDate.parse(data) );

               visitatore.addVisita(date);

               AggiornaListaVisite();
            }
            catch (Exception exc) {
                JOptionPane.showMessageDialog(this, "Formato errato" );
            }
        }
    }//GEN-LAST:event_btnAddVisitaMouseClicked

    private void btnAddValutazioneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddValutazioneMouseClicked
        GregorianCalendar visita = getVisitaSelezionata();
        
        if (visita == null) return;
        
        ValutazioneForm valutazioneForm = new ValutazioneForm(mainForm, true, visitatore, visita);
        valutazioneForm.setVisible(true);
        
        AggiornaListaValutazioni();
    }//GEN-LAST:event_btnAddValutazioneMouseClicked

    private void btnDelVisitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelVisitaMouseClicked
        GregorianCalendar visita = getVisitaSelezionata();
        
        if (visita == null) return;
        
        visitatore.deleteVisita(visita);
        
        AggiornaListaVisite();
    }//GEN-LAST:event_btnDelVisitaMouseClicked

    private void btnDelValutazioneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelValutazioneMouseClicked
        String szIVA = tblEspositori.getValueAt( tblEspositori.getSelectedRow(), 3 ).toString();
        
        visitatore.deleteValutazione( PI2Manager.getEspositore(szIVA));
        
        AggiornaListaValutazioni();
    }//GEN-LAST:event_btnDelValutazioneMouseClicked

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        String szParametriMancanti = "";
        
        if (txtNome.getText().length() == 0) szParametriMancanti += "\nNome";
        if (txtCognome.getText().length() == 0) szParametriMancanti += "\nCognome";
        if (txtCodiceFiscale.getText().length() == 0) szParametriMancanti += "\nCodice Fiscale";
        
        if (szParametriMancanti.length() > 0) {
            JOptionPane.showMessageDialog(this, "I seguenti parametri obbligatori non sono stati inseriti:" + szParametriMancanti );
            
            return;
        }
        
        // nuovo visitatore lo rilevo dalla mancanza di CF
        visitatore.setNome(txtNome.getText());
        visitatore.setCognome(txtCognome.getText());
        
        if (visitatore.getCodiceFiscale().length() == 0) {            
            visitatore.setCodiceFiscale(txtCodiceFiscale.getText());
            
            if (PI2Manager.addVisitatore(visitatore) == false) {
                    // azzero il dato per permetterne la correzione
                    visitatore.setCodiceFiscale( "" );

                    JOptionPane.showMessageDialog(this, "Un visitatore con lo stesso Codice Fiscale esiste gia'" );

                return;
            }
        }
        
        mainForm.setPendingSave();
        
        dispose();
    }//GEN-LAST:event_btnOKMouseClicked

    private GregorianCalendar getVisitaSelezionata()
    {
        // visita non selezionata
        if (lstVisite.getSelectedIndex() < 0) return null;
        
        GregorianCalendar visita = new GregorianCalendar();
        
        try
        {
            visita.setTime( formatDate.parse( lstVisite.getSelectedValue().toString() ) );
        }
        catch (Exception exc) {
            return null;
        }
        
        return visita;
    }
    
    private void AggiornaListaVisite()
    {
        GregorianCalendar [] aVisite = visitatore.getVisite();
            
        DefaultListModel oList = new DefaultListModel(); //(DefaultListModel)lstVisite.getModel();
        
        if (aVisite != null)
        {
            for ( Calendar visita : aVisite) {
                oList.addElement( formatDate.format( visita.getTime() ) );
            }
        }
        
        lstVisite.setModel(oList);
        
        btnDelVisita.setEnabled(false);
        
        AggiornaListaValutazioni();
    }
    
    private void AggiornaListaValutazioni()
    {
        DefaultTableModel tbl = (DefaultTableModel) tblEspositori.getModel();
        
        tbl.setRowCount(0);
        
        GregorianCalendar visita = getVisitaSelezionata();
        
        btnAddValutazione.setEnabled(false);
        btnDelValutazione.setEnabled(false);
        lblValutazioni.setText("--");
        
        if (visita == null) return;
        
        btnAddValutazione.setEnabled(true);
        
        lblValutazioni.setText("Espositori visitati il giorno: " + formatDate.format( visita.getTime() ) );
        
        for (IngeSoft.PI2.Valutazione valutazione : visitatore.getValutazioni()) {            
            // valutazione relativa ad altro giorno
            if (valutazione.visita.compareTo(visita) != 0) continue;
            
            IngeSoft.PI2.Espositore espositore = PI2Manager.getEspositore(valutazione.ivaEspositore);
            
            // espositore non esistente
            if (espositore == null) continue;
            
            tbl.addRow( new Object[]{
                espositore.getNome(),
                espositore.getPaese(),
                espositore.getArea(),
                espositore.getIVA(),
                valutazione.valutazione
            });
        }
    }
  
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VisitatoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VisitatoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VisitatoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VisitatoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VisitatoreForm().setVisible(true);
//            }
//        });
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddValutazione;
    private javax.swing.JButton btnAddVisita;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelValutazione;
    private javax.swing.JButton btnDelVisita;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblValutazioni;
    private javax.swing.JList lstVisite;
    private javax.swing.JTable tblEspositori;
    private javax.swing.JTextField txtCodiceFiscale;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
